// <auto-generated />
namespace TeduShop.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateFieldOrderDetail_Product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateFieldOrderDetail_Product));
        
        string IMigrationMetadata.Id
        {
            get { return "201710240229148_updateFieldOrderDetail_Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
