// <auto-generated />
namespace TeduShop.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addContent_Slide : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addContent_Slide));
        
        string IMigrationMetadata.Id
        {
            get { return "201710070718100_addContent_Slide"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
